spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.91.220.42:3306/shabao_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: master
    password: 19911105man
  redis:
    database: 5
    port: 6379
    host: 47.91.220.42
    password: 19911105man
    pool:
      max-active: 20
  devtools:
    restart:
      enabled: true  #是否开启
      additional-paths: src/main/java #需要重启的目录
      exclude: static/**,public/**,templates/** #不需要重启的目录

logging:
  level:
    root: INFO
    com.xiaoshabao.bill.bd.mapper: DEBUG
#  path: C:/logs
