spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.75.206.89:3306/shabao_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: master
    password: 19911105man
  redis:
    database: 2
    port: 6379
    host: 47.75.206.89
    password: 19911105man
    pool:
      max-active: 20
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
logging:
  level:
    root: INFO
    com.xiaoshabao.bill.bd.mapper: DEBUG